In [2]:
# import modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# reading the file
dataset = pd.read_csv('Placement_BeginnerTask01 (1).csv')
dataset.head()

,StudentID,CGPA,Internships,Projects,Workshops/Certifications,AptitudeTestScore,SoftSkillsRating,ExtracurricularActivities,PlacementTraining,SSC_Marks,HSC_Marks,PlacementStatus
0,1,7.5,1,1,1,65,4.4,No,No,61,79,NotPlaced
1,2,8.9,0,3,2,90,4.0,Yes,Yes,78,82,Placed
2,3,7.3,1,2,2,82,4.8,Yes,No,79,80,NotPlaced
3,4,7.5,1,1,2,85,4.4,Yes,Yes,81,80,Placed
4,5,8.3,1,2,2,86,4.5,Yes,Yes,74,88,Placed

In [3]:
# dropping StudentID column
dataset = dataset.drop('StudentID', axis=1)

In [4]:
# categorising columns for further labelling
dataset["ExtracurricularActivities"] = dataset["ExtracurricularActivities"].astype('category')
dataset["PlacementTraining"] = dataset["PlacementTraining"].astype('category')
dataset["PlacementStatus"] = dataset["PlacementStatus"].astype('category')

dataset.dtypes

CGPA                          float64
Internships                     int64
Projects                        int64
Workshops/Certifications        int64
AptitudeTestScore               int64
SoftSkillsRating              float64
ExtracurricularActivities    category
PlacementTraining            category
SSC_Marks                       int64
HSC_Marks                       int64
PlacementStatus              category
dtype: object

In [5]:
# labelling the columns
dataset["ExtracurricularActivities"] = dataset["ExtracurricularActivities"].cat.codes
dataset["PlacementTraining"] = dataset["PlacementTraining"].cat.codes
dataset["PlacementStatus"] = dataset["PlacementStatus"].cat.codes

# display dataset
dataset.head()

,CGPA,Internships,Projects,Workshops/Certifications,AptitudeTestScore,SoftSkillsRating,ExtracurricularActivities,PlacementTraining,SSC_Marks,HSC_Marks,PlacementStatus
0,7.5,1,1,1,65,4.4,0,0,61,79,0
1,8.9,0,3,2,90,4.0,1,1,78,82,1
2,7.3,1,2,2,82,4.8,1,0,79,80,0
3,7.5,1,1,2,85,4.4,1,1,81,80,1
4,8.3,1,2,2,86,4.5,1,1,74,88,1

In [6]:
# selecting the features and labels
X = dataset[['CGPA',
             'Internships',
             'Projects',
             'Workshops/Certifications',
             'AptitudeTestScore',
             'SoftSkillsRating',
             'ExtracurricularActivities',
             'PlacementTraining',
             'SSC_Marks',
             'HSC_Marks']]

Y = dataset['PlacementStatus']

0       0
1       1
2       0
3       1
4       1
       ..
9995    0
9996    1
9997    1
9998    1
9999    0
Name: PlacementStatus, Length: 10000, dtype: int8

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

In [8]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(max_iter=1000)
clf.fit(X_train, Y_train)

LogisticRegression(max_iter=1000)

In [9]:
Y_pred = clf.predict(X_test)
Y_pred

array([0, 0, 0, ..., 1, 1, 0], dtype=int8)

In [10]:
# printing the accuracy
clf.score(X_test, Y_test)

0.7945

In [11]:
#Confusion Matrix and Accuracy score
from sklearn.metrics import confusion_matrix, accuracy_score

print(confusion_matrix(Y_test, Y_pred))
print("Accuracy:", accuracy_score(Y_test, Y_pred))

[[954 218]
 [193 635]]
Accuracy: 0.7945

In [12]:
def placement_message(model, student_data):
    prob = model.predict_proba(student_data)[0][1]  # probability of being placed

    if prob >= 0.75:
        print(f"You have a HIGH chance of getting placed ({prob*100:.2f}%)")
    elif prob >= 0.5:
        print(f"You have a MODERATE chance of getting placed ({prob*100:.2f}%)")
    else:
        print(f"You have a LOW chance of getting placed ({prob*100:.2f}%)")

In [13]:
#[[9.6, 2, 3, 4, 78, 8.5, 1, 1, 85, 88]] high chance
#[[7.4, 1, 1, 2, 70, 7.5, 1, 0, 75, 78]] moderate chance
#[[3.4, 0, 1, 0, 40, 4.5, 0, 0, 55, 58]] low chance

In [14]:
data=eval(input("Enter the Data of the student in the format [CGPA,Internships,Projects,Workshops,AptitudeTestScore,SoftskillRating,ExtracurricularActivies,PlacementTraining,SSC_Marks,HSC_Marks]"))

Enter the Data of the student in the format [CGPA,Internships,Projects,Workshops,AptitudeTestScore,SoftskillRating,ExtracurricularActivies,PlacementTraining,SSC_Marks,HSC_Marks][[9.6, 2, 3, 4, 78, 8.5, 1, 1, 85, 88]]

In [15]:
placement_message(clf, data)

You have a HIGH chance of getting placed (99.44%)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(